name: Pack extensions
on:
  workflow_dispatch:
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Pack extensions for Firefox
        uses: ScratchAddons/packer-script@main
        id: firefox
        env:
          ENVIRONMENT: firefox
      - name: Upload packed extensions for Firefox
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.firefox.outputs.filename }}
          path: .dist/extracted/*
      - name: Pack extensions for Chrome
        uses: ScratchAddons/packer-script@main
        id: chrome
        env:
          ENVIRONMENT: chrome
      - name: Upload packed extensions for Chrome
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.chrome.outputs.filename }}
          path: .dist/extracted/*
