name: Update website changelog

on:
  push:
    branches:
      - changelog
      - master
    paths:
      - CHANGELOG.md
      - .github/workflows/update-changelog.yml

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ScratchAddons'

    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Changelog Update
          repo: ScratchAddons/website-v2
          token: ${{ steps.generate-token.outputs.token }}